#import "TypeCalculator.h"

@implementation TypeCalculator

- (NSDictionary *)effectivenessAgainst:(NSArray *)types {
    NSMutableDictionary *effectiveness = [@{} mutableCopy];
    for (NSString *attackingType in [self.typeChart allKeys]) {
        NSDecimalNumber *typeValue = N(1);
        for (NSString *defendingType in types) {
            typeValue = [typeValue decimalNumberByMultiplyingBy:self.typeChart[attackingType][defendingType]];
        }

        effectiveness[attackingType] = typeValue;
    }

    return effectiveness;
}

- (id)init {
    self = [super init];
    if (self) {
        self.typeChart = @{
                @"normal" : @{
                        @"normal" : N(1),
                        @"fighting" : N(1),
                        @"flying" : N(1),
                        @"poison" : N(1),
                        @"ground" : N(1),
                        @"rock" : N(0.5),
                        @"bug" : N(1),
                        @"ghost" : N(0),
                        @"steel" : N(0.5),
                        @"fire" : N(1),
                        @"water" : N(1),
                        @"grass" : N(1),
                        @"electric" : N(1),
                        @"psychic" : N(1),
                        @"ice" : N(1),
                        @"dragon" : N(1),
                        @"dark" : N(1),
                        @"fairy" : N(1)

                },
                @"fighting" : @{
                        @"normal" : N(2),
                        @"fighting" : N(1),
                        @"flying" : N(0.5),
                        @"poison" : N(0.5),
                        @"ground" : N(1),
                        @"rock" : N(2.5),
                        @"bug" : N(0.5),
                        @"ghost" : N(0),
                        @"steel" : N(2.5),
                        @"fire" : N(1),
                        @"water" : N(1),
                        @"grass" : N(1),
                        @"electric" : N(1),
                        @"psychic" : N(0.5),
                        @"ice" : N(2),
                        @"dragon" : N(1),
                        @"dark" : N(2),
                        @"fairy" : N(0.5)
                },
                @"flying" : @{
                        @"normal" : N(1),
                        @"fighting" : N(2),
                        @"flying" : N(1),
                        @"poison" : N(1),
                        @"ground" : N(1),
                        @"rock" : N(0.5),
                        @"bug" : N(2),
                        @"ghost" : N(1),
                        @"steel" : N(0.5),
                        @"fire" : N(1),
                        @"water" : N(1),
                        @"grass" : N(2),
                        @"electric" : N(0.5),
                        @"psychic" : N(1),
                        @"ice" : N(1),
                        @"dragon" : N(1),
                        @"dark" : N(1),
                        @"fairy" : N(1)
                },
                @"poison" : @{
                        @"normal" : N(1),
                        @"fighting" : N(1),
                        @"flying" : N(1),
                        @"poison" : N(0.5),
                        @"ground" : N(0.5),
                        @"rock" : N(0.5),
                        @"bug" : N(1),
                        @"ghost" : N(0.5),
                        @"steel" : N(0),
                        @"fire" : N(1),
                        @"water" : N(1),
                        @"grass" : N(2),
                        @"electric" : N(1),
                        @"psychic" : N(1),
                        @"ice" : N(1),
                        @"dragon" : N(1),
                        @"dark" : N(1),
                        @"fairy" : N(2)
                },
                @"ground" : @{
                        @"normal" : N(1),
                        @"fighting" : N(1),
                        @"flying" : N(0),
                        @"poison" : N(2),
                        @"ground" : N(1),
                        @"rock" : N(2),
                        @"bug" : N(0.5),
                        @"ghost" : N(1),
                        @"steel" : N(2),
                        @"fire" : N(2),
                        @"water" : N(1),
                        @"grass" : N(0.5),
                        @"electric" : N(2),
                        @"psychic" : N(1),
                        @"ice" : N(1),
                        @"dragon" : N(1),
                        @"dark" : N(1),
                        @"fairy" : N(1)
                },
                @"rock" : @{
                        @"normal" : N(1),
                        @"fighting" : N(0.5),
                        @"flying" : N(2),
                        @"poison" : N(1),
                        @"ground" : N(0.5),
                        @"rock" : N(1),
                        @"bug" : N(2),
                        @"ghost" : N(1),
                        @"steel" : N(0.5),
                        @"fire" : N(2),
                        @"water" : N(1),
                        @"grass" : N(1),
                        @"electric" : N(1),
                        @"psychic" : N(1),
                        @"ice" : N(2),
                        @"dragon" : N(1),
                        @"dark" : N(1),
                        @"fairy" : N(1)
                },
                @"bug" : @{
                        @"normal" : N(1),
                        @"fighting" : N(0.5),
                        @"flying" : N(0.5),
                        @"poison" : N(0.5),
                        @"ground" : N(1),
                        @"rock" : N(1),
                        @"bug" : N(1),
                        @"ghost" : N(0.5),
                        @"steel" : N(0.5),
                        @"fire" : N(0.5),
                        @"water" : N(1),
                        @"grass" : N(2),
                        @"electric" : N(1),
                        @"psychic" : N(2),
                        @"ice" : N(1),
                        @"dragon" : N(1),
                        @"dark" : N(2),
                        @"fairy" : N(0.5)
                },
                @"ghost" : @{
                        @"normal" : N(0),
                        @"fighting" : N(1),
                        @"flying" : N(1),
                        @"poison" : N(1),
                        @"ground" : N(1),
                        @"rock" : N(1),
                        @"bug" : N(1),
                        @"ghost" : N(2),
                        @"steel" : N(1),
                        @"fire" : N(1),
                        @"water" : N(1),
                        @"grass" : N(1),
                        @"electric" : N(1),
                        @"psychic" : N(2),
                        @"ice" : N(1),
                        @"dragon" : N(1),
                        @"dark" : N(0.5),
                        @"fairy" : N(1)
                },
                @"steel" : @{
                        @"normal" : N(1),
                        @"fighting" : N(1),
                        @"flying" : N(1),
                        @"poison" : N(1),
                        @"ground" : N(1),
                        @"rock" : N(2),
                        @"bug" : N(1),
                        @"ghost" : N(1),
                        @"steel" : N(0.5),
                        @"fire" : N(0.5),
                        @"water" : N(0.5),
                        @"grass" : N(1),
                        @"electric" : N(0.5),
                        @"psychic" : N(1),
                        @"ice" : N(2),
                        @"dragon" : N(1),
                        @"dark" : N(1),
                        @"fairy" : N(2)
                },
                @"fire" : @{
                        @"normal" : N(1),
                        @"fighting" : N(1),
                        @"flying" : N(1),
                        @"poison" : N(1),
                        @"ground" : N(1),
                        @"rock" : N(0.5),
                        @"bug" : N(2),
                        @"ghost" : N(1),
                        @"steel" : N(2),
                        @"fire" : N(0.5),
                        @"water" : N(0.5),
                        @"grass" : N(2),
                        @"electric" : N(1),
                        @"psychic" : N(1),
                        @"ice" : N(2),
                        @"dragon" : N(0.5),
                        @"dark" : N(1),
                        @"fairy" : N(1)
                },
                @"water" : @{
                        @"normal" : N(1),
                        @"fighting" : N(1),
                        @"flying" : N(1),
                        @"poison" : N(1),
                        @"ground" : N(2),
                        @"rock" : N(2),
                        @"bug" : N(1),
                        @"ghost" : N(1),
                        @"steel" : N(1),
                        @"fire" : N(2),
                        @"water" : N(0.5),
                        @"grass" : N(0.5),
                        @"electric" : N(1),
                        @"psychic" : N(1),
                        @"ice" : N(1),
                        @"dragon" : N(0.5),
                        @"dark" : N(1),
                        @"fairy" : N(1)
                },
                @"grass" : @{
                        @"normal" : N(1),
                        @"fighting" : N(1),
                        @"flying" : N(0.5),
                        @"poison" : N(0.5),
                        @"ground" : N(2),
                        @"rock" : N(2),
                        @"bug" : N(0.5),
                        @"ghost" : N(1),
                        @"steel" : N(0.5),
                        @"fire" : N(0.5),
                        @"water" : N(2),
                        @"grass" : N(0.5),
                        @"electric" : N(1),
                        @"psychic" : N(1),
                        @"ice" : N(1),
                        @"dragon" : N(0.5),
                        @"dark" : N(1),
                        @"fairy" : N(1)
                },
                @"electric" : @{
                        @"normal" : N(1),
                        @"fighting" : N(1),
                        @"flying" : N(2),
                        @"poison" : N(1),
                        @"ground" : N(0),
                        @"rock" : N(1),
                        @"bug" : N(1),
                        @"ghost" : N(1),
                        @"steel" : N(1),
                        @"fire" : N(1),
                        @"water" : N(2),
                        @"grass" : N(0.5),
                        @"electric" : N(0.5),
                        @"psychic" : N(1),
                        @"ice" : N(1),
                        @"dragon" : N(0.5),
                        @"dark" : N(1),
                        @"fairy" : N(1)
                },
                @"psychic" : @{
                        @"normal" : N(1),
                        @"fighting" : N(2),
                        @"flying" : N(1),
                        @"poison" : N(2),
                        @"ground" : N(1),
                        @"rock" : N(1),
                        @"bug" : N(1),
                        @"ghost" : N(1),
                        @"steel" : N(0.5),
                        @"fire" : N(1),
                        @"water" : N(1),
                        @"grass" : N(1),
                        @"electric" : N(1),
                        @"psychic" : N(0.5),
                        @"ice" : N(1),
                        @"dragon" : N(1),
                        @"dark" : N(0),
                        @"fairy" : N(1)
                },
                @"ice" : @{
                        @"normal" : N(1),
                        @"fighting" : N(1),
                        @"flying" : N(2),
                        @"poison" : N(1),
                        @"ground" : N(2),
                        @"rock" : N(1),
                        @"bug" : N(1),
                        @"ghost" : N(1),
                        @"steel" : N(0.5),
                        @"fire" : N(0.5),
                        @"water" : N(0.5),
                        @"grass" : N(2),
                        @"electric" : N(1),
                        @"psychic" : N(1),
                        @"ice" : N(0.5),
                        @"dragon" : N(2),
                        @"dark" : N(1),
                        @"fairy" : N(1)
                },
                @"dragon" : @{
                        @"normal" : N(1),
                        @"fighting" : N(1),
                        @"flying" : N(1),
                        @"poison" : N(1),
                        @"ground" : N(1),
                        @"rock" : N(1),
                        @"bug" : N(1),
                        @"ghost" : N(1),
                        @"steel" : N(0.5),
                        @"fire" : N(1),
                        @"water" : N(1),
                        @"grass" : N(1),
                        @"electric" : N(1),
                        @"psychic" : N(1),
                        @"ice" : N(1),
                        @"dragon" : N(2),
                        @"dark" : N(1),
                        @"fairy" : N(0)
                },
                @"dark" : @{
                        @"normal" : N(1),
                        @"fighting" : N(0.5),
                        @"flying" : N(1),
                        @"poison" : N(1),
                        @"ground" : N(1),
                        @"rock" : N(1),
                        @"bug" : N(1),
                        @"ghost" : N(2),
                        @"steel" : N(1),
                        @"fire" : N(1),
                        @"water" : N(1),
                        @"grass" : N(1),
                        @"electric" : N(1),
                        @"psychic" : N(2),
                        @"ice" : N(1),
                        @"dragon" : N(1),
                        @"dark" : N(0.5),
                        @"fairy" : N(0.5)
                },
                @"fairy" : @{
                        @"normal" : N(1),
                        @"fighting" : N(2),
                        @"flying" : N(1),
                        @"poison" : N(0.5),
                        @"ground" : N(1),
                        @"rock" : N(1),
                        @"bug" : N(1),
                        @"ghost" : N(1),
                        @"steel" : N(0.5),
                        @"fire" : N(0.5),
                        @"water" : N(1),
                        @"grass" : N(1),
                        @"electric" : N(1),
                        @"psychic" : N(1),
                        @"ice" : N(1),
                        @"dragon" : N(2),
                        @"dark" : N(2),
                        @"fairy" : N(1)
                }
        };
    }

    return self;
}

@end